name: 'Test Action'
author: 'danthe1st'
description: 'This is a test action'
inputs:
  text:
    description: 'Text to display'
    required: false
    default: 'Hello World'
outputs:
  time:
    description: 'Time needed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.text }}
branding:
  icon: sun
  color: blue
