name: 'Test Action'
author: 'danthe1st'
description: 'This is a test action'
inputs:
  token:
    description: 'Gh token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
branding:
  icon: sun
  color: blue
