name: 'Actions Command System'
author: 'danthe1st'
description: 'This action allows you to enter commands by writing comments to issues and pull requests.'
inputs:
  token:
    description: 'Gh token'
    required: true
  disabled:
    description: 'a list of disabled commands, seperated by spaces'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.disabled }}
branding:
  icon: terminal
  color: red
