name: 'Test Action'
author: 'danthe1st'
description: 'This is a test action'
inputs:
  url:
    description: 'URL of the JAR file (will be downloaded)'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - 'https://github.com/JDiscordBots/NightDream/wiki/NightDream.jar'
    - ${{ inputs.url }}
branding:
  icon: sun
  color: blue
