name: 'Test Action'
author: 'danthe1st'
description: 'This is a test action'
inputs:
  gh-token:
    description: 'The GitHub token'
    required: true
    default: no-token
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gh-token }}
branding:
  icon: sun
  color: blue
