#!/bin/bash
set -e

if ! [[ "$1" =~ '^[0-9]+$' ]] ; then
	sendComment "Syntax Error: first arg needs to be a number"
	exit
fi

if perm "$MESSAGE_AUTHOR" 3;then
	ids="$( comment "" "GET" "" "get-num" )"
	len="$(echo "$ids"|jq ". | length")"


	first=$((len - $1))
	last=$((len + 1))
	
	ids="$(echo "$ids"|jq ".[$first:$last][].id")"	


	echo "$ids" | while read id; do 
		comment "" "DELETE" "$id"
	done
else
	sendComment "Missing Permissions"
fi
