#!/bin/bash
# this command deletes the latest comments in the PR/issue the command is sent in
# arguments
#   the number of messages that should be deleted
# required permissions:
#   admin access on the repository
set -e

if ! [[ "$1" =~ ^[0-9]+$ ]] ; then
	sendComment "Syntax Error: first arg needs to be a number"
	exit
fi

if perm "$MESSAGE_AUTHOR" 3;then
	ids="$( comment "" "GET" "" "get-num" )"
	len="$(echo "$ids"|jq ". | length")"


	first=$((len - $1))
	last=$((len + 1))
	echo "$ids"|jq ".[$first:$last][].body">/dev/stderr	
	ids="$(echo "$ids"|jq ".[$first:$last][].id")"	


	echo "$ids" | while read -r id; do 
		comment "" "DELETE" "$id"
	done
else
	sendComment "Missing Permissions"
fi
