#!/bin/bash
# this command pings servers and displays the delay
# arguments:
# - the server IP/hostname (can be multiple servers seperated by spaces, default is github)
set -e
function getLatency(){
	out="$(ping -c 1 "$1"|cut -d$'\n' -f2|cut -d "=" -f4)"
	if [ -z "$out" ];then
		out="did not respond"
	fi
	echo "$out"
}
ln=$'\n'
if [ -z "$*" ]; then
	text="ping github.com: $(getLatency github.com)"
else
	text="pinging $*:$ln"
	for arg in "$@"; do
		text="$text${ln}ping $arg: $(getLatency "$arg")"
	done
fi
sendComment "$text"
