#!/bin/bash
set -e

#REPO_FULLNAME=$(jq -r ".repository.full_name" "$GITHUB_EVENT_PATH")
method="$2"
if [ -z "$method" ]; then
	method="POST"
fi
body="$1"
#if [[ -z "$msg" ]]; then
#	echo "no message provided" >/dev/stderr
#	exit -1
#fi
commentId="$3"

# TODO PR/commit commands
issueNum="$4"
path="repos/$REPO_FULLNAME/$API_PATH"
if [ -n "$issueNum" ]; then
	if [[ "$issueNum" =~ ^[^0-9]+$ ]]; then
		issueNum=$(jq -r ".$GH_EVENT_PATH.number" "$GITHUB_EVENT_PATH")
	fi
	path="$path/${issueNum}"
fi


path="$path/comments"
if [ -n "$commentId" ]; then
	path="$path/$commentId"
fi
sendAPI "$method" "$path" "$body"
