#!/bin/bash
# performs an action to the comments api
# Arguments:
# - the body that is sent to the api (if it is empty, it will be a HTTP request without any body)
# - the HTTP Method that should be used when calling the API (if it is empty, POST will be used)
# - the id of the comment, the api call refers to (if it is empty, the call will not refer to any specific comment)
# - the id of the issue/PR, the api call refers to (if it is empty, the request will not refer to any specific issue/PR, if it is not a number, the request will refer to the current issue)
# Output: 
# - the output of the request will be sent to stdout
set -e

#REPO_FULLNAME=$(jq -r ".repository.full_name" "$GITHUB_EVENT_PATH")
method="$2"
if [ -z "$method" ]; then
	method="POST"
fi
body="$1"
#if [[ -z "$msg" ]]; then
#	echo "no message provided" >/dev/stderr
#	exit -1
#fi
commentId="$3"

issueNum="$4"
path="repos/$REPO_FULLNAME/$API_PATH"
if [ -n "$issueNum" ]; then
	if [[ "$issueNum" =~ ^[^0-9]+$ ]]; then
		issueNum=$(jq -r "$GH_EVENT_PATH.number" "$GITHUB_EVENT_PATH")
	fi
	path="$path/${issueNum}"
fi


path="$path/comments"
if [ -n "$commentId" ]; then
	path="$path/$commentId"
fi
sendAPI "$method" "$path" "$body"
