#!/bin/bash
# tests the permission of a user
# arguments:
# - the user whose permission should be tested
# - the required permission level of the user (can be empty)
# Permission Levels:
# - 3...admin
# - 2...write/push access
# - 1...read/pull access
# - 0...no permission/invalid user
# Exit Code:
# - if a permission level is specified (second argument), 0 will be returned if the user owns this permission
# - if no permission level is specified, the permission level will be returned
# Output:
# - the name of the permission, the user has

set -e
user="$1"
req="$2"
perm="$(sendAPI GET "repos/$REPO_FULLNAME/collaborators/$user/permission")"
perm="$(echo "$perm" | jq -r ".permission")"
echo "$perm"
case "$perm" in
	admin)
		lv=3
		;;
	write)
		lv=2
		;;
	read)
		lv=1
		;;
	none)
		lv=0
		;;
	*)
		lv=0
		;;
esac
if [ -z "$req" ]; then
	exit "$lv"
fi
if [ "$lv" -ge "$req" ] ; then
	exit 0
fi
exit 1
