#!/bin/bash
BASE_URI=https://api.github.com
API_HEADER="Accept: application/vnd.github.v3+json"

method=POST

issueNum=$(jq -r ".issue.number" "$GITHUB_EVENT_PATH")
path="repos/$GITHUB_REPOSITORY/issues/${issueNum}/comments"
msg="test message"
body="{\"body\": \"$msg\"}"

echo "curl -X $method -s -u x-access-token:$GITHUB_TOKEN -H \"${API_HEADER}\" \"${BASE_URI}/${path}\" --data $body"
curl -X $method -s -u x-access-token:$GITHUB_TOKEN -H "${API_HEADER}" "${BASE_URI}/${path}" --data $body
