#!/bin/bash
BASE_URI=https://api.github.com
API_HEADER="Accept: application/vnd.github.v3+json"
BASE_REPO=$(echo "$pr_resp" | jq -r .base.repo.full_name)

method=POST

issueNum=$(jq -r ".issue.number" "$GITHUB_EVENT_PATH")
path="repos/$BASE_REPO/issues/${issueNum}/comments"
msg="test message"
body="{\"body\": \"$msg\"}"

echo "curl -X $method -s -u x-access-token:$GITHUB_TOKEN -H \"${API_HEADER}\" \"${BASE_URI}/${path}\" --data $body"
curl -X $method -s -u x-access-token:$GITHUB_TOKEN -H "${API_HEADER}" "${BASE_URI}/${path}" --data $body
