#!/bin/bash
set -e
BASE_URI=https://api.github.com
API_HEADER="Accept: application/vnd.github.v3+json"
AUTH_HEADER="authorization: token $GITHUB_TOKEN"
AGENT_HEADER="User-Agent: Actions-$REPO_FULLNAME"

method="$1"
path="$2"
body="$3"

echo "sending a $1 request to $path with the following body: $body" >/dev/stderr
if [ -z "$body" ]; then
  curl -X "$method" -s -H "${AUTH_HEADER}" -H "${AGENT_HEADER}" -H "${API_HEADER}" "${BASE_URI}/${path}"
else
  curl -X "$method" -s -H "${AUTH_HEADER}" -H "${AGENT_HEADER}" -H "${API_HEADER}" --data "$body" "${BASE_URI}/${path}"
fi
