#!/bin/bash
# this script sends a comment to the current issue/PR
# arguments:
#   all arguments contain the content of the comment
set -e
if [[ -z "$*" ]]; then
	echo "no message provided" >/dev/stderr
	exit 1
fi
msg=${*//\"/\\\"}
body="{\"body\": \"$msg\"}"
comment "$body" POST "" "get-num"
