#!/bin/bash
set -e
if [[ -z "$*" ]]; then
	echo "no message provided" >/dev/stderr
	exit -1
fi
# TODO escape msg or something like that, jq?
msg="${*@Q}"
body="{\"body\": \"$msg\"}"
comment "$body" POST "" "get-issue"
