me: static code analysis
on: [push]
jobs:
   SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v1
      - name: Run sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner
             -Dsonar.login=$SONAR_TOKEN
             -Dsonar.organization=danthe1st
             -Dsonar.host.url=https://sonarcloud.io/
             -Dsonar.projectKey=danthe1st_Actions-Command-System
             -Dsonar.sources=.
