on: 
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Runs the action
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: ./
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
    - name: Run Action
      uses: danthe1st/ActionsTest@master
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
