on: 
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Runs the action
    steps:
    - uses: danthe1st/Actions-Command-System@master
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
