on: [ push ]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Runs the action
    steps:
    - name: "send comment"
      run: 'curl -i -X POST -s -H "authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "User-Agent: Actions-danthe1st/ActionsTest" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/danthe1st/ActionsTest/issues/1/comments --data "{\"body\": \"/push\"}"'
